display_counter_bar_on_home_page:
  default: true
  type: bool
  description: "Display the counter bar below site header on Home page."

counter_bar_columns:
  type: list
  list_type: simple
  default: "Knowledge base, /c/knowledge-base/6, book"
  description:
    en: "Comma delimited in this order: link text, URL, icon"